[package]
name = "weight_on_mars"
version = "0.1.0"
authors = ["Kaushik Donthi <kaushikdr@ucla.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
libmath = "0.2.1"
