[package]
name = "html_server"
version = "0.1.0"
authors = ["Kaushik Donthi <kaushikdr@ucla.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
